In [3]:
import pandas as pd

file_path = '/content/df_for_ml_improved_up_to_2012.csv'


df = pd.read_csv(file_path)

print("DataFrame loaded successfully.")
print("Columns in the DataFrame:")
print(df.columns.tolist())

DataFrame loaded successfully.
Columns in the DataFrame:
['Unnamed: 0', 'case_id', 'year', 'height', 'width', 'size_inchsqr', 'price_usd', 'meanprice_year', 'min_price', 'max_price', 'medianprice_year', 'cnt_mean', 'cnt_max', 'cnt_median', 'cot_mean', 'cot_max', 'cot_median', 'ranking', 'fest_biennal', 'private_inst', 'public_inst', 'solo_show', 'group_show', 'age', 'estimate_min_usd', 'estimate_max_usd', 'estimate_center_usd', 'log10_estimate_geo_mean_usd', 'estimate_range_usd', 'Country - Austria', 'Country - China', 'Country - Dutch', 'Country - France', 'Country - Germany', 'Country - Japan', 'Country - Others', 'Country - Swiss', 'Country - UK', 'Country - USA', 'Continent - East Asia', 'Continent - Europe', 'Continent - North America', 'Continent - Others', 'Tier - 1', 'Tier - 2', 'Tier - 3', 'Tier - 4', 'Living - Argentina', 'Living - Australia', 'Living - Austria', 'Living - Brazil', 'Living - China', 'Living - Denmark', 'Living - Dutch', 'Living - France', 'Living - Germany', 'Living - India', 'Living - Italia', 'Living - Japan', 'Living - Mexico', 'Living - Norway', 'Living - Others', 'Living - South Africa', 'Living - Sweden', 'Living - Swiss', 'Living - Taiwan', 'Living - UK', 'Living - USA', 'price_usd_prev_5_mean', 'price_usd_prev_5_median', 'price_usd_prev_5_max', 'price_usd_prev_10_mean', 'price_usd_prev_10_median', 'price_usd_prev_10_max', 'price_same_size_prev_5_max', 'price_same_size_prev_5_mean', 'price_same_size_prev_5_median', 'price_same_size_prev_10_max', 'price_same_size_prev_10_mean', 'price_same_size_prev_10_median', 'matched_genre', 'matched_country', 'gender_NA', 'gender_female', 'gender_male', 'edu_NA', 'edu_abroad', 'edu_both', 'edu_domestic', 'degree_NA', 'grad', 'no_degree', 'undergrad', 'elite_school', 'elite_school_NA', 'non_elite_school', 'elite_award_not_received', 'elite_award_received', 'artwork_order', 'cnt_min', 'cot_min', 'Genre___Photography', 'Genre___Print', 'Genre___Sculpture', 'Genre___Painting', 'Genre___Others', 'price_usd_prev_5_min', 'price_usd_prev_10_min', 'price_same_size_prev_5_min', 'price_same_size_prev_10_min', 'eventdate', 'train']

In [4]:
keep_cols = [
    'case_id',
    'year',
    'height',
    'width',
    'size_inchsqr',
    'price_usd',

    'ranking',
    'age',

    'estimate_min_usd',
    'estimate_max_usd',
    'estimate_center_usd',
    'estimate_range_usd',

    'Country - Austria',
    'Country - China',
    'Country - Dutch',
    'Country - France',
    'Country - Germany',
    'Country - Japan',
    'Country - Others',
    'Country - Swiss',
    'Country - UK',
    'Country - USA',

    'Continent - East Asia',
    'Continent - Europe',
    'Continent - North America',
    'Continent - Others',

    'Tier - 1',
    'Tier - 2',
    'Tier - 3',
    'Tier - 4',

    'Genre___Photography',
    'Genre___Print',
    'Genre___Sculpture',
    'Genre___Painting',
    'Genre___Others',

    'eventdate'
]

art = df[keep_cols].copy()

print(art.shape)
art.head()

(34200, 36)

,case_id,year,height,width,size_inchsqr,price_usd,ranking,age,estimate_min_usd,estimate_max_usd,...,Tier - 1,Tier - 2,Tier - 3,Tier - 4,Genre___Photography,Genre___Print,Genre___Sculpture,Genre___Painting,Genre___Others,eventdate
0,43406,1996.0,39.0,32.0,1248.0,323694.0,10.0,58.0,231210.000000,308280.000000,...,1,0,0,0,1,0,0,0,0,1996-06-26
1,86747,1996.0,51.0,63.0,3213.0,161847.0,5794.0,77.0,123312.000000,184968.000000,...,1,0,0,0,1,0,0,0,0,1996-06-26
2,27266,1996.0,22.0,17.0,374.0,3902.0,33.0,59.0,4552.333333,5853.000000,...,0,0,1,0,0,0,0,1,1,1996-11-30
3,43428,1996.0,36.0,27.0,972.0,12357.0,10.0,58.0,15608.842105,18210.315789,...,0,0,1,0,1,0,0,0,0,1996-11-30
4,60906,1996.0,71.0,89.0,6319.0,13008.0,90.0,61.0,13008.000000,19512.000000,...,0,0,1,0,0,0,0,1,1,1996-11-30

In [5]:
country_cols = [
    'Country - Austria',
    'Country - China',
    'Country - Dutch',
    'Country - France',
    'Country - Germany',
    'Country - Japan',
    'Country - Others',
    'Country - Swiss',
    'Country - UK',
    'Country - USA'
]

def get_country(row):
    for col in country_cols:
        if row[col] == 1:
            return col.replace('Country - ', '')
    return 'Unknown'

art['Country'] = art.apply(get_country, axis=1)

In [6]:
art['Country'].value_counts()

Country
USA        16354
UK          9291
France      2794
Others      2084
Germany     1414
Austria     1215
Dutch        500
China        289
Swiss        257
Japan          2
Name: count, dtype: int64

In [7]:
continent_cols = [
    'Continent - East Asia',
    'Continent - Europe',
    'Continent - North America',
    'Continent - Others'
]

def get_continent(row):
    for col in continent_cols:
        if row[col] == 1:
            return col.replace('Continent - ', '')
    return 'Unknown'

art['Continent'] = art.apply(get_continent, axis=1)

art['Continent'].value_counts()

Continent
Europe           16966
North America    16354
Others             584
East Asia          296
Name: count, dtype: int64

In [8]:
genre_cols = [
    'Genre___Photography',
    'Genre___Print',
    'Genre___Sculpture',
    'Genre___Painting',
    'Genre___Others'
]

def get_genre(row):
    for col in genre_cols:
        if row[col] == 1:
            return col.replace('Genre___', '')
    return 'Unknown'

art['Genre'] = art.apply(get_genre, axis=1)

art['Genre'].value_counts()

Genre
Photography    11616
Print           8888
Sculpture       7267
Painting        6316
Others           113
Name: count, dtype: int64

In [9]:
tier_cols = [
    'Tier - 1',
    'Tier - 2',
    'Tier - 3',
    'Tier - 4'
]

def get_tier(row):
    for col in tier_cols:
        if row[col] == 1:
            return col.replace('Tier - ', 'Tier ')
    return 'Unknown'

art['Tier'] = art.apply(get_tier, axis=1)

art['Tier'].value_counts()

Tier
Tier 1    21906
Tier 4     5538
Tier 2     3596
Tier 3     3160
Name: count, dtype: int64

In [10]:
drop_cols = country_cols + continent_cols + genre_cols + tier_cols

art = art.drop(columns=drop_cols)

print(art.columns.tolist())

['case_id', 'year', 'height', 'width', 'size_inchsqr', 'price_usd', 'ranking', 'age', 'estimate_min_usd', 'estimate_max_usd', 'estimate_center_usd', 'estimate_range_usd', 'eventdate', 'Country', 'Continent', 'Genre', 'Tier']

In [11]:
art.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34200 entries, 0 to 34199
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   case_id              34200 non-null  int64
 1   year                 34200 non-null  float64
 2   height               34200 non-null  float64
 3   width                34200 non-null  float64
 4   size_inchsqr         34200 non-null  float64
 5   price_usd            34200 non-null  float64
 6   ranking              34079 non-null  float64
 7   age                  34200 non-null  float64
 8   estimate_min_usd     34200 non-null  float64
 9   estimate_max_usd     34200 non-null  float64
 10  estimate_center_usd  34200 non-null  float64
 11  estimate_range_usd   34200 non-null  float64
 12  eventdate            34200 non-null  object
 13  Country              34200 non-null  object
 14  Continent            34200 non-null  object
 15  Genre                34200 non-null  object
 16  Tier                 34200 non-null  object
dtypes: float64(11), int64(1), object(5)
memory usage: 4.4+ MB

In [12]:
art.describe()

,case_id,year,height,width,size_inchsqr,price_usd,ranking,age,estimate_min_usd,estimate_max_usd,estimate_center_usd,estimate_range_usd
count,34200.000000,34200.000000,34200.000000,34200.000000,34200.000000,3.420000e+04,34079.000000,34200.000000,3.420000e+04,3.420000e+04,3.420000e+04,34200.000000
mean,57209.310965,2007.342982,35.918697,36.124170,1964.619842,7.300583e+04,384.796766,60.599737,4.667417e+04,6.537280e+04,5.602349e+04,18698.628912
std,33235.551842,3.541547,27.996566,30.501939,7606.746652,1.790383e+05,529.521667,13.590737,1.053952e+05,1.463728e+05,1.257821e+05,42210.903085
min,13.000000,1996.000000,0.790000,0.310000,0.744000,3.800000e+01,3.000000,28.000000,1.000000e+02,2.000000e+02,1.500000e+02,1.000000
25%,28294.750000,2005.000000,17.000000,17.000000,301.698150,7.123000e+03,69.000000,50.000000,5.006214e+03,7.403833e+03,6.282561e+03,2000.000000
50%,55837.500000,2008.000000,28.350000,28.000000,816.000000,1.769100e+04,188.000000,61.000000,1.200000e+04,1.781469e+04,1.500000e+04,5000.000000
75%,87562.250000,2010.000000,47.990000,47.010000,2287.781750,5.189800e+04,526.000000,72.000000,3.500000e+04,4.969917e+04,4.010339e+04,14124.200000
max,114265.000000,2012.000000,959.840000,959.840000,921292.900000,4.060853e+06,13983.000000,93.000000,1.395660e+06,1.794420e+06,1.595040e+06,546360.000000

In [13]:
art.isnull().sum().sort_values(ascending=False)

ranking                121
case_id                  0
year                     0
width                    0
height                   0
size_inchsqr             0
price_usd                0
age                      0
estimate_min_usd         0
estimate_max_usd         0
estimate_center_usd      0
estimate_range_usd       0
eventdate                0
Country                  0
Continent                0
Genre                    0
Tier                     0
dtype: int64

In [14]:
print("Rows:", len(art))
print("Unique artworks:", art['case_id'].nunique())
print("Years:", art['year'].min(), "to", art['year'].max())
print("Countries:", art['Country'].nunique())
print("Genres:", art['Genre'].nunique())
print("Tiers:", art['Tier'].nunique())

Rows: 34200
Unique artworks: 34200
Years: 1996.0 to 2012.0
Countries: 10
Genres: 5
Tiers: 4

In [15]:
art.groupby('Country')['price_usd'].agg(
    ['count', 'mean', 'median', 'max']
).sort_values('median', ascending=False)

         count           mean   median        max
Country
China      289   63416.512111  35980.0   618244.0
UK        9291  109947.677968  25844.0  4060853.0
USA      16354   73586.343769  20000.0  3218500.0
Dutch      500   30159.440000  12563.5   589405.0
Germany   1414   31220.649222  10763.5  1030537.0
Japan        2   10296.500000  10296.5    13219.0
Others    2084   27637.996161  10005.0  1395790.0
France    2794   39443.795634   9776.0  1711559.0
Austria   1215   17959.125926   8990.0   377412.0
Swiss      257   18081.229572   6201.0   734650.0

In [16]:
art.groupby('Genre')['price_usd'].agg(
    ['count', 'mean', 'median', 'max']
).sort_values('median', ascending=False)

             count           mean   median        max
Genre
Photography  11616  147997.986312  46398.0  4060853.0
Print         8888   44534.544442  16250.0  2840000.0
Sculpture     7267   35362.632310  11875.0  2044658.0
Painting      6316   19529.109563   8525.0  1482500.0
Others         113   13324.274336   6124.0   206500.0

In [17]:
art = art.drop(columns=['ranking'])

In [18]:
art.groupby('Tier')['price_usd'].agg(
    ['count', 'mean', 'median', 'max']
).sort_values('median', ascending=False)

        count          mean   median        max
Tier
Tier 1  21906  98973.126312  27500.0  4060853.0
Tier 2   3596  39977.259177  12610.0  1562201.0
Tier 3   3160  24838.110127   9508.5  1711559.0
Tier 4   5538  19221.276815   7443.0  1129805.0

In [21]:
import numpy as np

art['estimate_status'] = np.select(
    [
        art['price_usd'] < art['estimate_min_usd'],
        art['price_usd'] > art['estimate_max_usd']
    ],
    [
        'Below Estimate',
        'Above Estimate'
    ],
    default='Within Estimate'
)

In [22]:
art['estimate_status'].value_counts()

estimate_status
Above Estimate     14751
Within Estimate    14025
Below Estimate      5424
Name: count, dtype: int64

In [23]:
art.groupby('estimate_status')['price_usd'].agg(
    ['count', 'mean', 'median']
)

                 count           mean   median
estimate_status
Above Estimate   14751  103376.801030  27500.0
Below Estimate    5424   32478.572456   8000.0
Within Estimate  14025   56736.143957  15000.0

In [24]:
art['estimate_ratio'] = (
    art['price_usd'] / art['estimate_center_usd']
)

art['estimate_ratio'].describe()

count    34200.000000
mean         1.346114
std          1.058193
min          0.001880
25%          0.875000
50%          1.093750
75%          1.517857
max         64.000000
Name: estimate_ratio, dtype: float64

In [25]:
country_estimate = art.groupby('Country').agg(
    artworks=('case_id', 'count'),
    median_price=('price_usd', 'median'),
    median_estimate_ratio=('estimate_ratio', 'median'),
    above_estimate_pct=('estimate_status',
                       lambda x: (x == 'Above Estimate').mean() * 100)
).sort_values('median_estimate_ratio', ascending=False)

country_estimate

         artworks  median_price  median_estimate_ratio  above_estimate_pct
Country
China         289       35980.0               1.444444           67.474048
Japan           2       10296.5               1.309231           50.000000
Dutch         500       12563.5               1.214286           52.000000
UK           9291       25844.0               1.128333           45.527930
USA         16354       20000.0               1.120000           44.826954
France       2794        9776.0               1.053868           39.871152
Germany      1414       10763.5               1.045714           40.452617
Others       2084       10005.0               1.000000           34.404990
Swiss         257        6201.0               0.933333           31.906615
Austria      1215        8990.0               0.916667           20.493827

In [26]:
tier_estimate = art.groupby('Tier').agg(
    artworks=('case_id', 'count'),
    median_price=('price_usd', 'median'),
    median_estimate_ratio=('estimate_ratio', 'median'),
    above_estimate_pct=('estimate_status',
                       lambda x: (x == 'Above Estimate').mean() * 100)
).sort_values('median_estimate_ratio', ascending=False)

tier_estimate

        artworks  median_price  median_estimate_ratio  above_estimate_pct
Tier
Tier 2      3596       12610.0               1.200000           50.222469
Tier 1     21906       27500.0               1.133333           45.905231
Tier 3      3160        9508.5               1.000000           31.740506
Tier 4      5538        7443.0               1.000000           34.055616

In [27]:
art[['height', 'width', 'size_inchsqr', 'age',
     'price_usd']].describe()

             height         width   size_inchsqr           age     price_usd
count  34200.000000  34200.000000   34200.000000  34200.000000  3.420000e+04
mean      35.918697     36.124170    1964.619842     60.599737  7.300583e+04
std       27.996566     30.501939    7606.746652     13.590737  1.790383e+05
min        0.790000      0.310000       0.744000     28.000000  3.800000e+01
25%       17.000000     17.000000     301.698150     50.000000  7.123000e+03
50%       28.350000     28.000000     816.000000     61.000000  1.769100e+04
75%       47.990000     47.010000    2287.781750     72.000000  5.189800e+04
max      959.840000    959.840000  921292.900000     93.000000  4.060853e+06

In [28]:
art[['height', 'width', 'size_inchsqr', 'age',
     'price_usd']].corr(method='spearman')['price_usd'].sort_values()

age            -0.067136
height          0.389729
width           0.397709
size_inchsqr    0.408632
price_usd       1.000000
Name: price_usd, dtype: float64

In [29]:
year_summary = art.groupby('year').agg(
    artworks=('case_id', 'count'),
    total_value=('price_usd', 'sum'),
    median_price=('price_usd', 'median'),
    above_estimate_pct=('estimate_status',
                       lambda x: (x == 'Above Estimate').mean() * 100)
).reset_index()

year_summary

      year  artworks  total_value  median_price  above_estimate_pct
0   1996.0         6     525864.0       12682.5           16.666667
1   1997.0       100    5363427.0       13747.0           17.000000
2   1998.0       206   11462434.0       16840.0           33.495146
3   1999.0       330   17509944.0       11517.5           36.060606
4   2000.0      1167   45913114.0       11000.0           32.990574
5   2001.0      1016   39705498.0       11588.0           32.086614
6   2002.0       998   55195971.0       14000.0           30.260521
7   2003.0      1402   56540308.0       12000.0           38.659058
8   2004.0      1951   95080096.0       14548.0           43.516146
9   2005.0      2633  140687436.0       15000.0           43.486517
10  2006.0      2755  168092909.0       16672.0           47.005445
11  2007.0      3859  369905802.0       24000.0           50.894014
12  2008.0      3355  349686685.0       22500.0           40.357675
13  2009.0      2719  170552660.0       17500.0           39.499816
14  2010.0      3585  267098984.0       17991.0           46.025105
15  2011.0      4111  361079295.0       19281.0           45.682316
16  2012.0      4007  342398961.0       21250.0           44.447217

In [30]:
art.to_csv("art_powerbi.csv", index=False)

In [31]:
art.shape

(34200, 18)

In [32]:
art.columns.tolist()

['case_id',
 'year',
 'height',
 'width',
 'size_inchsqr',
 'price_usd',
 'age',
 'estimate_min_usd',
 'estimate_max_usd',
 'estimate_center_usd',
 'estimate_range_usd',
 'eventdate',
 'Country',
 'Continent',
 'Genre',
 'Tier',
 'estimate_status',
 'estimate_ratio']

In [33]:
from google.colab import files

files.download("art_powerbi.csv")